# Generated by Django 4.1 on 2022-08-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="env",
            new_name="end",
        ),
    ]
