# Generated by Django 4.1 on 2022-08-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_audit", "0002_rename_env_event_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
