# Generated by Django 4.1 on 2022-08-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_audit", "0003_event_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="summary",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
